version: '3.8'

services:
  runtime-node:
    container_name: inventory-node
    image: node:21.2-alpine3.17
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "3000:3000"

  server-nginx:
    container_name: inventory-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/usr/share/nginx/html
    depends_on:
      - language-php

  language-php:
    container_name: inventory-php
    image: php:8.1-fpm
    volumes:
      - ./app:/var/www/html
    depends_on:
        - database-msql

  database-postgresql:
    container_name: inventory-postgresql
    image: postgres:13
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  database-msql:
    container_name: inventory-mysql
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password

volumes:
  database-mysql:
